/** @type {import('eslint').L.Config[]} */
import pluginPrettier from 'eslint-plugin-prettier';

export default [
  { ignores: ['tailwind.css', 'dist/', 'node_modules/', 'graphify-out/', 'coverage/'] },
  {
    files: ['**/*.js', '**/*.mjs'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: {
        browser: true,
        node: true,
        es2022: true,
        vitest: true,
        // Browser globals for jsdom tests
        document: 'readonly',
        window: 'readonly',
        localStorage: 'readonly',
        File: 'readonly',
        Event: 'readonly',
        fetch: 'readonly',
        crypto: 'readonly',
        Blob: 'readonly',
        btoa: 'readonly',
        atob: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        HTMLCanvasElement: 'readonly',
        console: 'readonly',
        URL: 'readonly',
        navigator: 'readonly',
        indexedDB: 'readonly',
        IDBKeyRange: 'readonly',
        IDBRequest: 'readonly',
        FileReader: 'readonly',
        Image: 'readonly',
        location: 'readonly',
        self: 'readonly',
        caches: 'readonly',
        HTMLElement: 'readonly',
        HTMLSelectElement: 'readonly',
        HTMLInputElement: 'readonly',
        __dirname: 'readonly',
        global: 'readonly',
        module: 'readonly',
        exports: 'readonly',
        require: 'readonly',
        process: 'readonly',
        Buffer: 'readonly',
        structuredClone: 'readonly',
        vi: 'readonly',
        beforeEach: 'readonly',
        afterEach: 'readonly',
        afterAll: 'readonly',
      },
    },
    plugins: {
      prettier: pluginPrettier,
    },
    rules: {
      'prettier/prettier': 'error',
      'no-console': ['warn', { allow: ['warn', 'error'] }],
      'prefer-const': 'error',
      'no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrors: 'none' },
      ],
      'no-undef': 'error',
    },
  },
  {
    files: ['tests/**/*.test.js', 'tests/setup.js', 'vitest.config.js'],
    languageOptions: {
      globals: {
        describe: true,
        it: true,
        expect: true,
        beforeEach: true,
        afterEach: true,
        vi: true,
        // Browser globals for jsdom tests
        document: 'readonly',
        window: 'readonly',
        localStorage: 'readonly',
        File: 'readonly',
        Event: 'readonly',
        fetch: 'readonly',
        crypto: 'readonly',
        Blob: 'readonly',
        btoa: 'readonly',
        atob: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        HTMLCanvasElement: 'readonly',
      },
    },
    rules: {
      'no-unused-vars': 'off',
    },
  },
  {
    files: [
      'tools/**/*.mjs',
      'netlify/functions/**/*.js',
      'playwright.config.js',
      'postcss.config.js',
      'tailwind.config.js',
    ],
    languageOptions: {
      globals: {
        node: true,
        console: 'readonly',
        Buffer: 'readonly',
        writeFile: 'readonly',
        process: 'readonly',
        module: 'readonly',
        exports: 'readonly',
        require: 'readonly',
        __dirname: 'readonly',
      },
    },
    rules: {
      'no-unused-vars': 'off',
      'no-console': 'off',
    },
  },
  {
    files: ['scripts/sw.js', 'scripts/sw-update.js'],
    languageOptions: {
      globals: {
        self: 'readonly',
        caches: 'readonly',
        navigator: 'readonly',
        location: 'readonly',
        console: 'readonly',
      },
    },
  },
];
